minio-server:
  tty: true
  image: quay.io/webcenter/alpine-minio:latest
  volumes_from:
    - minio-volume
    - rancher-cattle-metadata
  environment:
    - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
    - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    - CONFD_BACKEND=${CONFD_BACKEND}
    - CONFD_NODES=${CONFD_NODES}
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: minio-volume, rancher-cattle-metadata
rancher-cattle-metadata:
  net: none
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  image: quay.io/webcenter/rancher-cattle-metadata:latest
minio-volume:
  net: none
  labels:
    io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    io.rancher.container.hostname_override: container_name
    io.rancher.container.start_once: true
  volumes:
    - /data
  volume_driver: local
  command: /bin/true
  image: alpine:3.5
