version: '2'
services:
  minio-server:
    tty: true
    image: webcenter/alpine-minio:2017-02-16
    volumes:
      data-volume:/data
    volume_driver: local
    volumes_from:
      - rancher-cattle-metadata
    environment:
      - MINIO_CONFIG_minio.access.key=${MINIO_ACCESS_KEY}
      - MINIO_CONFIG_minio.secret.key=${MINIO_SECRET_KEY}
      - MINIO_DISKS_1=disk1
      - CONFD_BACKEND=${CONFD_BACKEND}
      - CONFD_NODES=${CONFD_NODES}
      - CONFD_PREFIX_KEY=${CONFD_PREFIX}
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.sidekicks: rancher-cattle-metadata
  rancher-cattle-metadata:
    net: none
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
    image: webcenter/rancher-cattle-metadata:1.0.0

volumes:
  data-volume:
